### ISSUE TITLE
Allow custom "content index" title through settings

### ISSUE THREAD

**Issue by LoyalPotato** [LoyalPotato/potato-indexer#3]
Currently the user needs to leave the index title as is to make sure it can find and replace it.
In order to allow some customization of that title, it'd be nice to have a settings that allowed that.

**Comment by synj00** [comment]
Currently in Potato Indexer 1.1.1 and Obsidian 1.4.16 index falls below the first H1 

To replicate - 

Create new Document 
Name Document
Create H1 Headings
Generate index for current note
Index falls below first H1

# First
## Content Index

 - [First](#First)
 - [Second](#Second)
 - [Third](#Third)


some content

# Second

Some Content

# Third

Some Content

It may have something to do with how Obsidian handles Titles 
Since it automatically inserts the first H1 as the title does not show the first H1 and the first actual H1 is interpreted as the title. 

I'm not familiar enough with typescript to make a pull request unfortunately but I think it is here. You can just seek first H1 nd then add index above 

[indexSvc.ts](https://github.com/LoyalPotato/potato-indexer/blob/master/src/indexSvc.ts)
... 
  const lines = content.split("\n");
  let index = "\n## Content Index\n\n";
  const indexPos: number[] = [];
...
and also [.editorconfig](https://github.com/LoyalPotato/potato-indexer/blob/master/.editorconfig)

# top-most EditorConfig file
root = true

**Comment by LoyalPotato** [comment]
@synj00 Can you put this in another issue as it doesn't seem related to the current issue

**Comment by synj00** [comment]
> Currently the user needs to leave the index title as is to make sure it can find and replace it. In order to allow some customization of that title, it'd be nice to have a settings that allowed that.

Oh so seems like an Obsidian indexing based issue? I can look through the forums to see if I can find anything, if not, I can ask for an enhancement for Obsidian. I cant believe this isn't a core plugin actually. Thanks and sorry for the delayed response and moving the issue for me.
